default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    host: <%= ENV['DB_HOST'] || 'dpg-d81sglg3kofs73c3jri0-a.virginia-postgres.render.com' %>
    database: <%= ENV['DB_NAME'] || 'dhanva_2' %>
    username: <%= ENV['DB_USERNAME'] || 'dhanva_2_user' %>
    password: <%= ENV['DB_PASSWORD'] || 's0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
  cable:
    <<: *primary_development
  queue:
    <<: *primary_development
  cache:
    <<: *primary_development

test:
  primary: &primary_test
    <<: *default
    database: marali_sante_test
  cable:
    <<: *primary_test
  queue:
    <<: *primary_test
  cache:
    <<: *primary_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhanva_2_user:s0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B@dpg-d81sglg3kofs73c3jri0-a.virginia-postgres.render.com/dhanva_2' %>
    host: <%= ENV['DB_HOST'] || 'dpg-d81sglg3kofs73c3jri0-a.virginia-postgres.render.com' %>
    database: <%= ENV['DB_NAME'] || 'dhanva_2' %>
    username: <%= ENV['DB_USERNAME'] || 'dhanva_2_user' %>
    password: <%= ENV['DB_PASSWORD'] || 's0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
  cable:
    <<: *primary_production
  queue:
    <<: *primary_production
  cache:
    <<: *primary_production