default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    host: <%= ENV['DB_HOST'] || 'dpg-d6mceedm5p6s73fo3ul0-a.virginia-postgres.render.com' %>
    database: <%= ENV['DB_NAME'] || 'dhan02' %>
    username: <%= ENV['DB_USERNAME'] || 'dhan02_user' %>
    password: <%= ENV['DB_PASSWORD'] || 'moCc2BsPe3pOTbOK5hc6dOrydgae32Zq' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
  cable:
    <<: *primary_development
  queue:
    <<: *primary_development
  cache:
    <<: *primary_development

test:
  primary: &primary_test
    <<: *default
    database: marali_sante_test
  cable:
    <<: *primary_test
  queue:
    <<: *primary_test
  cache:
    <<: *primary_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhan02_user:moCc2BsPe3pOTbOK5hc6dOrydgae32Zq@dpg-d6mceedm5p6s73fo3ul0-a.virginia-postgres.render.com/dhan02' %>
    host: <%= ENV['DB_HOST'] || 'dpg-d6mceedm5p6s73fo3ul0-a.virginia-postgres.render.com' %>
    database: <%= ENV['DB_NAME'] || 'dhan02' %>
    username: <%= ENV['DB_USERNAME'] || 'dhan02_user' %>
    password: <%= ENV['DB_PASSWORD'] || 'moCc2BsPe3pOTbOK5hc6dOrydgae32Zq' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
  cable:
    <<: *primary_production
  queue:
    <<: *primary_production
  cache:
    <<: *primary_production