default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    host: <%= ENV['DB_HOST'] || 'dpg-d6l4rgc50q8c73bmcnt0-a.oregon-postgres.render.com' %>
    database: <%= ENV['DB_NAME'] || 'marali_sante' %>
    username: <%= ENV['DB_USERNAME'] || 'marali_sante_user' %>
    password: <%= ENV['DB_PASSWORD'] || '6Yeikjs3h6sEyoskxcmqsHmcRh9xgYHf' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
  cable:
    <<: *primary_development
  queue:
    <<: *primary_development
  cache:
    <<: *primary_development

test:
  primary: &primary_test
    <<: *default
    database: marali_sante_test
  cable:
    <<: *primary_test
  queue:
    <<: *primary_test
  cache:
    <<: *primary_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://marali_sante_user:6Yeikjs3h6sEyoskxcmqsHmcRh9xgYHf@dpg-d6l4rgc50q8c73bmcnt0-a.oregon-postgres.render.com/marali_sante' %>
    host: <%= ENV['DB_HOST'] || 'dpg-d6l4rgc50q8c73bmcnt0-a.oregon-postgres.render.com' %>
    database: <%= ENV['DB_NAME'] || 'marali_sante' %>
    username: <%= ENV['DB_USERNAME'] || 'marali_sante_user' %>
    password: <%= ENV['DB_PASSWORD'] || '6Yeikjs3h6sEyoskxcmqsHmcRh9xgYHf' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
  cable:
    <<: *primary_production
  queue:
    <<: *primary_production
  cache:
    <<: *primary_production